remote_theme: yous/whiteglass
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

title: Comfortably Geek
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
excerpt_separator: "!!!!---"
paginate: 5
exclude: [node_modules]

