theme: jekyll-whiteglass
remote_theme: jekyll-whiteglass
plugins:
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
excerpt_separator: "!!!!---"
paginate: 5
exclude: [node_modules]

